"""
Django settings for dropshipping project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import hashlib
import re
from pathlib import Path
from decouple import config
import os
import sys
from email.utils import formataddr, parseaddr
from urllib.parse import parse_qs, unquote, urlparse
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = BASE_DIR / 'logs'


def _read_local_env_file():
    values = {}
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        return values

    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip()
        if not key:
            continue
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]
        values[key] = value

    return values


LOCAL_ENV_VALUES = _read_local_env_file()


def _clean_config_value(value, default=''):
    if value is None:
        return default

    cleaned = str(value).strip()
    if len(cleaned) >= 2 and cleaned[0] == cleaned[-1] and cleaned[0] in {'"', "'"}:
        cleaned = cleaned[1:-1].strip()
    return cleaned


def _build_development_secret_key():
    seed = str(BASE_DIR).replace('\\', '/').encode('utf-8')
    digest = hashlib.sha256(seed).hexdigest()
    return f"django-dev-{digest}-change-me"

def _to_bool(value, default=False):
    """Parse environment booleans safely without raising."""
    if value is None:
        return default
    if isinstance(value, bool):
        return value

    normalized = str(value).strip().lower()
    if normalized in {'1', 'true', 'yes', 'on', 'y', 't', 'debug', 'development'}:
        return True
    if normalized in {'0', 'false', 'no', 'off', 'n', 'f', 'prod', 'production', 'release'}:
        return False
    return default


def _csv_to_list(value):
    if not value:
        return []
    return [item.strip() for item in str(value).split(',') if item.strip()]


def _is_local_host(host):
    normalized = (host or '').strip().lower()
    if not normalized:
        return True
    if ':' in normalized:
        normalized = normalized.split(':', 1)[0]
    return normalized in {'localhost', '127.0.0.1', 'testserver'}


def _read_config(name, default=''):
    return _clean_config_value(config(name, default=default), default)


def _env_or_config(name, default=''):
    if RUNNING_ON_RENDER or _to_bool(os.getenv('DJANGO_PRODUCTION', 'False'), default=False):
        return _clean_config_value(os.getenv(name, default), default)
    # Prefer the repo's .env locally so machine-wide shell vars do not force
    # production behavior during development.
    if name in LOCAL_ENV_VALUES:
        return _clean_config_value(LOCAL_ENV_VALUES.get(name, default), default)
    if name in os.environ:
        return _clean_config_value(os.environ.get(name, ''), default)
    return _read_config(name, default)


def _env_or_config_any(names, default=''):
    for name in names:
        value = _env_or_config(name, '')
        if value:
            return value
    return default


RENDER_EXTERNAL_HOSTNAME = str(os.getenv('RENDER_EXTERNAL_HOSTNAME', '')).strip()
_BASE_DIR_POSIX = str(BASE_DIR).replace('\\', '/')
RENDER_PATH_HINT = _BASE_DIR_POSIX.startswith('/opt/render/project/')
RUNNING_ON_RENDER = (
    _to_bool(os.getenv('RENDER', 'False'), default=False)
    or bool(RENDER_EXTERNAL_HOSTNAME)
    or bool(str(os.getenv('RENDER_SERVICE_ID', '')).strip())
    or bool(str(os.getenv('RENDER_INSTANCE_ID', '')).strip())
    or RENDER_PATH_HINT
)


def _db_value(name, default=''):
    """
    In Render, use runtime environment only for DB settings.
    Outside Render, allow .env fallback for local development.
    """
    if RUNNING_ON_RENDER:
        return _clean_config_value(os.getenv(name, default), default)
    return _env_or_config(name, default)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_raw_secret_key = _env_or_config('SECRET_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _to_bool(_env_or_config('DEBUG', 'False'), default=False)
if RUNNING_ON_RENDER:
    # Never default to DEBUG=True on hosted runtime.
    DEBUG = _to_bool(os.getenv('DEBUG', 'False'), default=False)

if _raw_secret_key:
    SECRET_KEY = _raw_secret_key
elif DEBUG:
    # Keep a stable secret locally so reloads do not invalidate sessions.
    SECRET_KEY = _build_development_secret_key()
else:
    raise ImproperlyConfigured('SECRET_KEY must be set when DEBUG is False.')

ALLOWED_HOSTS = _csv_to_list(_env_or_config('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver'))
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

IS_PRODUCTION = _to_bool(_env_or_config('DJANGO_PRODUCTION', 'False'), default=False)
if not IS_PRODUCTION and not DEBUG:
    IS_PRODUCTION = any(not _is_local_host(host) for host in ALLOWED_HOSTS)
if RUNNING_ON_RENDER:
    IS_PRODUCTION = True

if IS_PRODUCTION and (SECRET_KEY.startswith('django-insecure-') or len(SECRET_KEY) < 50):
    raise ImproperlyConfigured('Use a strong, non-default SECRET_KEY when running in production.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django.contrib.sites',
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    # 'crispy_forms',
    # 'crispy_bootstrap5',
    # 'phonenumber_field',
    # 'django_extensions',
    # 'django_filters',
    
    # Local apps
    'core.apps.CoreConfig',
    'accounts.apps.AccountsConfig',
    'products.apps.ProductsConfig',
    'orders.apps.OrdersConfig',
    'sellers',
    'cart',
    'reviews',
    'payments',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.DynamicCSRFMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dropshipping.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
                'core.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'dropshipping.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# Priority:
# 1) DATABASE_URL (common on Render/Railway/Heroku)
# 2) DB_ENGINE + DB_NAME + DB_USER + DB_PASSWORD + DB_HOST + DB_PORT
# 3) Local SQLite fallback for development
DATABASE_URL = _db_value('DATABASE_URL', '')
if not DATABASE_URL:
    DATABASE_URL = _db_value('POSTGRES_URL', '')
if not DATABASE_URL:
    DATABASE_URL = _db_value('POSTGRESQL_URL', '')

RAW_DB_ENGINE = _db_value('DB_ENGINE', '')
DB_ENGINE_ALIASES = {
    'sqlite3': 'django.db.backends.sqlite3',
    'postgres': 'django.db.backends.postgresql',
    'postgresql': 'django.db.backends.postgresql',
    'mysql': 'django.db.backends.mysql',
}
DB_ENGINE = DB_ENGINE_ALIASES.get(RAW_DB_ENGINE, RAW_DB_ENGINE)

if DATABASE_URL:
    parsed = urlparse(DATABASE_URL)
    scheme = (parsed.scheme or '').lower()

    if scheme in {'postgres', 'postgresql'}:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': unquote((parsed.path or '').lstrip('/')),
                'USER': unquote(parsed.username or ''),
                'PASSWORD': unquote(parsed.password or ''),
                'HOST': parsed.hostname or '',
                'PORT': str(parsed.port or ''),
            }
        }

        query_params = parse_qs(parsed.query or '')
        ssl_mode = (query_params.get('sslmode') or [''])[0]
        if ssl_mode:
            DATABASES['default']['OPTIONS'] = {'sslmode': ssl_mode}
    elif scheme in {'sqlite', 'sqlite3'}:
        sqlite_path = unquote((parsed.path or '').lstrip('/'))
        sqlite_name = sqlite_path if os.path.isabs(sqlite_path) else str(BASE_DIR / sqlite_path)
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': sqlite_name,
            }
        }
    else:
        raise ImproperlyConfigured(f"Unsupported DATABASE_URL scheme: '{scheme}'")
elif DB_ENGINE:
    default_db_name = str(BASE_DIR / 'db.sqlite3') if DB_ENGINE == 'django.db.backends.sqlite3' else ''
    db_name = _db_value('DB_NAME', '') or _db_value('PGDATABASE', default_db_name)
    db_user = _db_value('DB_USER', '') or _db_value('PGUSER', '')
    db_password = _db_value('DB_PASSWORD', '') or _db_value('PGPASSWORD', '')
    db_host = _db_value('DB_HOST', '') or _db_value('PGHOST', '')
    db_port = _db_value('DB_PORT', '') or _db_value('PGPORT', '5432')

    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': db_name,
        }
    }
    if DB_ENGINE != 'django.db.backends.sqlite3':
        DATABASES['default'].update({
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': db_port,
        })
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

if IS_PRODUCTION and DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    raise ImproperlyConfigured(
        'SQLite is not supported in production. Configure PostgreSQL with DATABASE_URL or DB_* variables.'
    )

CURRENT_COMMAND = sys.argv[1] if len(sys.argv) > 1 else ''
SKIP_DB_GUARD_COMMANDS = {'collectstatic'}

if (
    RUNNING_ON_RENDER
    and DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql'
    and CURRENT_COMMAND not in SKIP_DB_GUARD_COMMANDS
):
    db_host = (DATABASES['default'].get('HOST') or '').strip()
    if _is_local_host(db_host):
        raise ImproperlyConfigured(
            'Render runtime is trying to use localhost PostgreSQL. Set DATABASE_URL from your Render PostgreSQL service.'
        )


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_METADATA_CLASS': 'core.drf_metadata.EmptyMetadata',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': config('DRF_THROTTLE_ANON', default='120/min'),
        'user': config('DRF_THROTTLE_USER', default='240/min'),
    },
}

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Django Allauth
SITE_ID = 1
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary / Media storage settings
import cloudinary
import cloudinary.uploader
import cloudinary.api

CLOUDINARY_CLOUD_NAME = _env_or_config('CLOUDINARY_CLOUD_NAME', '').strip()
CLOUDINARY_API_KEY = _env_or_config('CLOUDINARY_API_KEY', '').strip()
CLOUDINARY_API_SECRET = _env_or_config('CLOUDINARY_API_SECRET', '').strip()

USE_CLOUDINARY_STORAGE = all([
    CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET,
])
# Default to Cloudinary whenever credentials are available so admin and user
# uploads behave the same in local development and production.
USE_CLOUDINARY_IN_DEBUG = _to_bool(_env_or_config('USE_CLOUDINARY_IN_DEBUG', 'True'), default=True)
if DEBUG and not USE_CLOUDINARY_IN_DEBUG:
    USE_CLOUDINARY_STORAGE = False

if USE_CLOUDINARY_STORAGE:
    cloudinary.config(
        cloud_name=CLOUDINARY_CLOUD_NAME,
        api_key=CLOUDINARY_API_KEY,
        api_secret=CLOUDINARY_API_SECRET,
    )
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': CLOUDINARY_API_KEY,
        'API_SECRET': CLOUDINARY_API_SECRET,
    }
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = _env_or_config_any(('EMAIL_HOST', 'SMTP_HOST', 'MAIL_HOST'), 'smtp.gmail.com')
EMAIL_PORT = int(_env_or_config_any(('EMAIL_PORT', 'SMTP_PORT', 'MAIL_PORT'), '587') or 587)
EMAIL_USE_TLS = _to_bool(_env_or_config_any(('EMAIL_USE_TLS', 'SMTP_USE_TLS', 'MAIL_USE_TLS'), 'True'), default=True)
EMAIL_USE_SSL = _to_bool(_env_or_config_any(('EMAIL_USE_SSL', 'SMTP_USE_SSL', 'MAIL_USE_SSL'), 'False'), default=False)
EMAIL_TIMEOUT = int(_env_or_config_any(('EMAIL_TIMEOUT', 'SMTP_TIMEOUT', 'MAIL_TIMEOUT'), '20') or 20)
EMAIL_HOST_USER = _env_or_config_any(
    ('EMAIL_HOST_USER', 'EMAIL_USER', 'SMTP_USERNAME', 'SMTP_USER', 'MAIL_USERNAME', 'MAIL_USER'),
    '',
)
EMAIL_HOST_PASSWORD = _env_or_config_any(
    ('EMAIL_HOST_PASSWORD', 'EMAIL_PASSWORD', 'SMTP_PASSWORD', 'MAIL_PASSWORD', 'GMAIL_APP_PASSWORD'),
    '',
)
if 'gmail' in EMAIL_HOST.lower() and EMAIL_HOST_PASSWORD:
    # Gmail App Passwords are often copied as four groups; SMTP needs the compact token.
    EMAIL_HOST_PASSWORD = re.sub(r'\s+', '', EMAIL_HOST_PASSWORD)
if EMAIL_USE_SSL and EMAIL_USE_TLS:
    EMAIL_USE_TLS = False
SITE_NAME = _env_or_config('SITE_NAME', 'Skyraa Store')
EMAIL_FROM_NAME = _env_or_config_any(('EMAIL_FROM_NAME', 'MAIL_FROM_NAME'), SITE_NAME)
_DEFAULT_FROM_EMAIL_RAW = _env_or_config_any(('DEFAULT_FROM_EMAIL', 'EMAIL_FROM', 'MAIL_FROM_ADDRESS'), EMAIL_HOST_USER)
if '<' in _DEFAULT_FROM_EMAIL_RAW and '>' in _DEFAULT_FROM_EMAIL_RAW:
    _default_from_address = parseaddr(_DEFAULT_FROM_EMAIL_RAW)[1]
elif _DEFAULT_FROM_EMAIL_RAW:
    _default_from_address = _DEFAULT_FROM_EMAIL_RAW
else:
    _default_from_address = ''

if 'gmail' in EMAIL_HOST.lower() and EMAIL_HOST_USER and _default_from_address.lower() != EMAIL_HOST_USER.lower():
    # Gmail is strict about the envelope sender in hosted environments.
    _default_from_address = EMAIL_HOST_USER

DEFAULT_FROM_EMAIL = formataddr((EMAIL_FROM_NAME, _default_from_address)) if _default_from_address else ''
FRONTEND_URL = _env_or_config('FRONTEND_URL', 'http://127.0.0.1:8000')

# Payment Settings
RAZORPAY_KEY_ID = _env_or_config('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = _env_or_config('RAZORPAY_KEY_SECRET', '')

STRIPE_PUBLISHABLE_KEY = _env_or_config('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = _env_or_config('STRIPE_SECRET_KEY', '')

# Admin credentials and payment destination
ADMIN_EMAIL = (_env_or_config('ADMIN_EMAIL', '') or '').strip().lower()
ADMIN_PASSWORD = _env_or_config('ADMIN_PASSWORD', '')
ADMIN_UPI_ID = _env_or_config('ADMIN_UPI_ID', '')

_allow_env_admin_sync_raw = _env_or_config('ALLOW_ENV_ADMIN_SYNC', '')
if _allow_env_admin_sync_raw:
    ALLOW_ENV_ADMIN_SYNC = _to_bool(_allow_env_admin_sync_raw, default=False)
else:
    # Default to enabled when admin credentials are configured so fresh production DBs can bootstrap login.
    ALLOW_ENV_ADMIN_SYNC = bool(ADMIN_EMAIL and ADMIN_PASSWORD)

# Redis Configuration
CELERY_BROKER_URL = config('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('REDIS_URL', default='redis://localhost:6379/0')

# Security Settings
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = _to_bool(_env_or_config('USE_X_FORWARDED_HOST', 'True' if not DEBUG else 'False'), default=not DEBUG)
SECURE_SSL_REDIRECT = _to_bool(_env_or_config('SECURE_SSL_REDIRECT', 'True' if not DEBUG else 'False'), default=not DEBUG)
SECURE_HSTS_SECONDS = int(_env_or_config('SECURE_HSTS_SECONDS', str(31536000 if not DEBUG else 0)) or 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _to_bool(
    _env_or_config('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True' if not DEBUG else 'False'),
    default=not DEBUG
)
SECURE_HSTS_PRELOAD = _to_bool(
    _env_or_config('SECURE_HSTS_PRELOAD', 'True' if not DEBUG else 'False'),
    default=not DEBUG
)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

SESSION_COOKIE_SECURE = _to_bool(_env_or_config('SESSION_COOKIE_SECURE', 'True' if not DEBUG else 'False'), default=not DEBUG)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = _env_or_config('SESSION_COOKIE_SAMESITE', 'Lax')
SESSION_COOKIE_AGE = int(_env_or_config('SESSION_COOKIE_AGE', '43200') or 43200)
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = _to_bool(_env_or_config('SESSION_EXPIRE_AT_BROWSER_CLOSE', 'False'), default=False)

CSRF_COOKIE_SECURE = _to_bool(_env_or_config('CSRF_COOKIE_SECURE', 'True' if not DEBUG else 'False'), default=not DEBUG)
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = _env_or_config('CSRF_COOKIE_SAMESITE', 'Lax' if DEBUG else 'Strict')
CSRF_USE_SESSIONS = _to_bool(_env_or_config('CSRF_USE_SESSIONS', 'False'), default=False)

if IS_PRODUCTION:
    # Enforce secure defaults in production even if environment values are lax.
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = max(SECURE_HSTS_SECONDS, 31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Allow debug previews from localhost-style origins unless explicitly disabled.
ALLOW_DYNAMIC_CSRF_ORIGINS = DEBUG and _to_bool(
    _env_or_config('ALLOW_DYNAMIC_CSRF_ORIGINS', 'True'),
    default=True
)

# CORS Settings
_default_origins = 'http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://127.0.0.1:8000'
CORS_ALLOWED_ORIGINS = _csv_to_list(_env_or_config('CORS_ALLOWED_ORIGINS', _default_origins))
CORS_ALLOW_CREDENTIALS = _to_bool(_env_or_config('CORS_ALLOW_CREDENTIALS', 'True'), default=True)
CORS_ALLOW_ALL_ORIGINS = DEBUG and _to_bool(_env_or_config('CORS_ALLOW_ALL_ORIGINS', 'False'), default=False)
if CORS_ALLOW_ALL_ORIGINS and CORS_ALLOW_CREDENTIALS:
    CORS_ALLOW_CREDENTIALS = False

# CSRF Settings - Secure but functional for development
CSRF_TRUSTED_ORIGINS = _csv_to_list(_env_or_config('CSRF_TRUSTED_ORIGINS', _default_origins))

# Request / upload hardening
DATA_UPLOAD_MAX_MEMORY_SIZE = int(_env_or_config('DATA_UPLOAD_MAX_MEMORY_SIZE', '10485760') or 10485760)
FILE_UPLOAD_MAX_MEMORY_SIZE = int(_env_or_config('FILE_UPLOAD_MAX_MEMORY_SIZE', '5242880') or 5242880)
DATA_UPLOAD_MAX_NUMBER_FIELDS = int(_env_or_config('DATA_UPLOAD_MAX_NUMBER_FIELDS', '2000') or 2000)
FILE_UPLOAD_PERMISSIONS = 0o644

# Auth hardening
ADMIN_LOGIN_FAILURE_LIMIT = int(_env_or_config('ADMIN_LOGIN_FAILURE_LIMIT', '5') or 5)
ADMIN_LOGIN_LOCKOUT_SECONDS = int(_env_or_config('ADMIN_LOGIN_LOCKOUT_SECONDS', '900') or 900)

LOG_DIR.mkdir(exist_ok=True)
_log_handlers = ['console'] if RUNNING_ON_RENDER else ['console', 'file']

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': LOG_DIR / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': _log_handlers,
        'level': 'INFO',
    },
}

# Custom Settings
COMMISSION_RATE = config('COMMISSION_RATE', default=0.10, cast=float)  # 10% commission
SHIPPING_COST = config('SHIPPING_COST', default=50, cast=float)
TAX_RATE = config('TAX_RATE', default=0.18, cast=float)  # 18% GST

# Frontend URL is configured in the email section above with local .env support.
