# Generated by Django 6.0.2 on 2026-02-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='default_currency',
            field=models.CharField(default='INR', max_length=3, verbose_name='default currency'),
        ),
    ]
