# Generated by Django 6.0.2 on 2026-03-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_default_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(blank=True, default='SwiftCart is an online shopping platform registered in 2026.', verbose_name='site description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='SwiftCart', max_length=100, verbose_name='site name'),
        ),
    ]
