# Generated by Django 5.1.6 on 2026-04-26 03:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesettings_site_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10, verbose_name='media type')),
                ('media_file', models.FileField(upload_to='hero_media/', verbose_name='media file')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('display_duration', models.PositiveIntegerField(default=2, verbose_name='display duration (seconds)')),
            ],
            options={
                'verbose_name': 'Media Content',
                'verbose_name_plural': 'Media Contents',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
