# Generated by Codex on 2026-04-27

from django.db import migrations, models


OLD_NAME = 'SwiftCart'
NEW_NAME = 'Skyraa Store'
OLD_DESCRIPTION = 'SwiftCart is an online shopping platform registered in 2026.'
NEW_DESCRIPTION = 'Skyraa Store is an online shopping platform registered in 2026.'


def rename_existing_site_settings(apps, schema_editor):
    SiteSettings = apps.get_model('core', 'SiteSettings')

    for site_settings in SiteSettings.objects.all():
        updated_fields = []

        if site_settings.site_name == OLD_NAME:
            site_settings.site_name = NEW_NAME
            updated_fields.append('site_name')

        if site_settings.site_description == OLD_DESCRIPTION:
            site_settings.site_description = NEW_DESCRIPTION
            updated_fields.append('site_description')

        if updated_fields:
            site_settings.save(update_fields=updated_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mediacontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(
                blank=True,
                default=NEW_DESCRIPTION,
                verbose_name='site description',
            ),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(
                default=NEW_NAME,
                max_length=100,
                verbose_name='site name',
            ),
        ),
        migrations.RunPython(rename_existing_site_settings, migrations.RunPython.noop),
    ]
