# Generated by Django 5.1.6 on 2026-05-03 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_update_site_brand_to_skyraa_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('mobile', models.CharField(max_length=20, verbose_name='mobile number')),
                ('website_type', models.CharField(choices=[('ecommerce', 'E-commerce Store'), ('business', 'Business Website'), ('portfolio', 'Portfolio/Resume'), ('blog', 'Blog/News Website'), ('restaurant', 'Restaurant/Food Business'), ('education', 'Educational Platform'), ('healthcare', 'Healthcare/Medical'), ('real-estate', 'Real Estate'), ('other', 'Other')], max_length=20, verbose_name='website type')),
                ('budget', models.CharField(choices=[('5000-10000', '₹5,000 - ₹10,000'), ('10000-25000', '₹10,000 - ₹25,000'), ('25000-50000', '₹25,000 - ₹50,000'), ('50000-100000', '₹50,000 - ₹1,00,000'), ('100000+', '₹1,00,000+')], max_length=20, verbose_name='budget range')),
                ('details', models.TextField(blank=True, verbose_name='project details')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='admin notes')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='contacted at')),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='quoted amount')),
            ],
            options={
                'verbose_name': 'Website Request',
                'verbose_name_plural': 'Website Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MediaContent',
        ),
    ]
