# Generated by Django 5.1.6 on 2026-05-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_websiterequest_delete_mediacontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiterequest',
            name='budget',
            field=models.CharField(choices=[('100-200', '₹100 - ₹200'), ('800-1000', '₹800 - ₹1,000'), ('3000-5000', '₹3,000 - ₹5,000'), ('10000-20000', '₹10,000 - ₹20,000'), ('5000-10000', '₹5,000 - ₹10,000'), ('10000-25000', '₹10,000 - ₹25,000'), ('25000-50000', '₹25,000 - ₹50,000'), ('50000-100000', '₹50,000 - ₹1,00,000'), ('100000+', '₹1,00,000+')], max_length=20, verbose_name='budget range'),
        ),
        migrations.AlterField(
            model_name='websiterequest',
            name='website_type',
            field=models.CharField(choices=[('simple-html', 'Simple Website (HTML & CSS only)'), ('database-website', 'Website with Database + Login/Signup'), ('api-website', 'Advanced Website with Database + API + Login/Signup'), ('android-app', 'Full Android App with All Features + Notifications'), ('ecommerce', 'E-commerce Store'), ('business', 'Business Website'), ('portfolio', 'Portfolio/Resume'), ('blog', 'Blog/News Website'), ('restaurant', 'Restaurant/Food Business'), ('education', 'Educational Platform'), ('healthcare', 'Healthcare/Medical'), ('real-estate', 'Real Estate'), ('other', 'Other')], max_length=20, verbose_name='website type'),
        ),
    ]
